// User Actions
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';
export const SET_USER_LIST = 'SET_USER_LIST';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_TO_USER_ARRAY = 'ADD_TO_USER_ARRAY';

// Registration Actions
export const DELETE_REGISTRATION = 'DELETE_REGISTRATION';
export const PATCH_REGISTRATION = 'PATCH_REGISTRATION';

// Tournament Actions
export const SET_TOURNAMENTS_ARE_LOADING = 'SET_TOURNAMENTS_ARE_LOADING';
export const GET_TOURNAMENT = 'GET_TOURNAMENT';
export const SET_TOURNAMENT_LIST = 'SET_TOURNAMENT_LIST';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
